### ISSUE TITLE
Isolate the operating environments of different algorithms

### ISSUE THREAD

**Issue by meua** [dora-rs/dora-drives#51]
**Is your feature request related to a problem? Please describe.**
Different algorithms depend on different versions of python and different versions of dependent installation packages. Packages that result in algorithmic dependencies are very prone to conflicts. 

**Describe the solution you'd like**
Therefore, it is expected that different algorithms can run in isolation and independently. Reduce the interference between algorithms.

**Describe alternatives you've considered**
Use namespaces or virtual environments to isolate different algorithm running environments

**Comment by haixuanTao** [comment]
So, for the dora-drives starter project explicitly, we don't want to have too many environments to manage with its own set of dependencies. You can use the shell command within the dataflow if you want to use different python interpreter with custom node. 
Ex:

```yaml
  - id: object_detection
    custom:
      source: shell
      args: conda activate env3.10 && python object_detection_custom_node.py
      inputs:
        image: webcam/image
      outputs:
        - bbox
```
